### ISSUE TITLE
Checklist to introduce multibyte fixes

### ISSUE THREAD

**Issue by miya0001** [cjk4wp/wordpress#3]
Following is the checklist to open track tickets for multibyte fixes for WordPress.

* [x] The length of the excerpt should be 110 in Japanese.
* [x] The length of the excerpt in RSS should be 110 in Japanese.
* [x] Double-width space should be used as search delimiter.
* [x] Email should be encoded with ISO-2022-JP
* [ ] Characters in pingback and trackback should not be broken.
* [x] The filename which is in Japanese should be encoded md5.
* [x] The length of comment in dashboard should be 40.
* [x] The length of draft in dashboard should be 40.
* [x] Incremental search of link in tinymce should fire from 2 chars.
* [ ] We don't need italic in dashboard.

Related:

* https://eastcoder.com/code/wp-multibyte-patch/
* https://github.com/jawordpressorg/automated-testing-for-wordpress-ja
* https://github.com/miya0001/wp-multibyte-patch

**Comment by miya0001** [comment]
List of tickets

https://docs.google.com/spreadsheets/d/13oGbc7AqEN6OUvmze-JDCKXDdruFqsxqSAdI7-b6Lho/edit#gid=0
